-- MySQL Script generated by MySQL Workbench
-- 08/24/17 08:25:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Competicao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Competicao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Competicao` DEFAULT CHARACTER SET utf8 ;
USE `Competicao` ;

-- -----------------------------------------------------
-- Table `Competicao`.`Atleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Competicao`.`Atleta` (
  `idAtleta` INT NOT NULL AUTO_INCREMENT,
  `Nome_Atleta` VARCHAR(60) NOT NULL,
  `Sexo` CHAR(1) NOT NULL,
  `dtNascimento` DATE NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAtleta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Competicao`.`Penalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Competicao`.`Penalidade` (
  `idPenalidade` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Atleta_idAtleta` INT NOT NULL,
  PRIMARY KEY (`idPenalidade`),
  INDEX `fk_Penalidade_Atleta_idx` (`Atleta_idAtleta` ASC),
  CONSTRAINT `fk_Penalidade_Atleta`
    FOREIGN KEY (`Atleta_idAtleta`)
    REFERENCES `Competicao`.`Atleta` (`idAtleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
